### ISSUE TITLE
RuntimeError not showing up in Sentry log

### ISSUE THREAD

**Issue by monicao** [getsentry/sentry-elixir#144]
sentry_version: 3.0.0
erlang: OTP 19/erts-8.3
elixir: 1.4.1

I noticed that certain errors don't get reported by sentry. 
For example, I can see this error in my server log, but it does not show up in the sentry error list.

This error was raised as a RuntimeError as `raise "Could not retrieve resource from Stripe."`

I have `use_error_logger` set to true. I tested that the `ThisWillError.real()` error from the docs is reported when I paste that code into a remote_console.

```
%{"error" => %{"code" => "incorrect_cvc",
    "message" => "Your card's security code is incorrect.", "param" => "cvc",
    "type" => "card_error"}}
2017-03-25 00:40:55.646 [error] GenServer #PID<0.1732.0> terminating
** (RuntimeError) Could not retrieve resource from Stripe.
    (myapp) lib/stripe_client.ex:41: MyApp.StripeClient.post!/2
    (myapp) lib/billing/payment_source.ex:18: MyApp.Billing.PaymentSource.add!/2
    (myapp) web/channels/users_channel.ex:84: MyApp.UsersChannel.handle_in/3
    (phoenix) lib/phoenix/channel/server.ex:226: anonymous fn/4 in Phoenix.Channel.Server.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3


  =CRASH REPORT==== 25-Mar-2017::00:40:55 ===
  crasher:
    initial call: Elixir.Phoenix.Channel.Server:init/1
    pid: <0.1732.0>
    registered_name: []
    exception exit: {#{'__exception__' => true,
                       '__struct__' => 'Elixir.RuntimeError',
                       message =>
                           <<"Could not retrieve resource from Stripe.">>},
                     [{'Elixir.MyApp.StripeClient','post!',2,
                          [{file,"lib/stripe_client.ex"},{line,41}]},
                      {'Elixir.MyApp.Billing.PaymentSource','add!',2,
                          [{file,"lib/billing/payment_source.ex"},{line,18}]},
                      {'Elixir.MyApp.UsersChannel',handle_in,3,
                          [{file,"web/channels/users_channel.ex"},{line,84}]},
                      {'Elixir.Phoenix.Channel.Server',
                          '-handle_info/2-fun-4-',4,
                          [{file,"lib/phoenix/channel/server.ex"},{line,226}]},
                      {gen_server,try_dispatch,4,
                          [{file,"gen_server.erl"},{line,601}]},
                      {gen_server,handle_msg,5,
                          [{file,"gen_server.erl"},{line,667}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,247}]}]}
      in function  gen_server:terminate/7 (gen_server.erl, line 812)
    ancestors: [<0.1727.0>]
    messages: []
    links: [<0.1583.0>,<0.1727.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 19937
  neighbours:
```

**Comment by mitchellhenke** [comment]
Hi, thanks for reporting this!

Do you know if other errors within Phoenix channels report properly?

**Comment by monicao** [comment]
I'll try it out in a bit and let you know.

**Comment by monicao** [comment]
Tested generating an `UndefinedFunctionError`.

```elixir
  # web/channels/users_channel.ex
  def handle_in("get_main_data", %{}, socket) do
    BadModule.does_not_exist()
    # some more code
  end
```

This error is reported in the server log, but the error does not show up in sentry.

```
[info] USERS_CHANNEL: [socket: %Phoenix.Socket{assigns: %{user_id: 10}, channel: MyApp.UsersChannel, channel_pid: #PID<0.1735.0>, endpoint: MyApp.Endpoint, handler: MyApp.UserSocket, id: nil, joined: true, pubsub_server: MyApp.PubSub, ref: "2", serializer: Phoenix.Transports.WebSocketSerializer, topic: "user:10", transport: Phoenix.Transports.WebSocket, transport_name: :websocket, transport_pid: #PID<0.1734.0>}]
2017-03-31 04:42:39.300 [error] GenServer #PID<0.1735.0> terminating
** (UndefinedFunctionError) function BadModule.does_not_exist/0 is undefined (module BadModule is not available)
    BadModule.does_not_exist()
    (myapp) web/channels/users_channel.ex:39: MyApp.UsersChannel.handle_in/3
    (phoenix) lib/phoenix/channel/server.ex:226: anonymous fn/4 in Phoenix.Channel.Server.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "get_main_data", payload: %{}, ref: "2", topic: "user:10"}
State: %Phoenix.Socket{assigns: %{user_id: 10}, channel: MyApp.UsersChannel, channel_pid: #PID<0.1735.0>, endpoint: MyApp.Endpoint, handler: MyApp.UserSocket, id: nil, joined: true, pubsub_server: MyApp.PubSub, ref: nil, serializer: Phoenix.Transports.WebSocketSerializer, topic: "user:10", transport: Phoenix.Transports.WebSocket, transport_name: :websocket, transport_pid: #PID<0.1734.0>}

=CRASH REPORT==== 31-Mar-2017::04:42:39 ===
  crasher:
    initial call: Elixir.Phoenix.Channel.Server:init/1
    pid: <0.1735.0>
    registered_name: []
    exception exit: {undef,
                        [{'Elixir.BadModule',does_not_exist,[],[]},
                         {'Elixir.MyApp.UsersChannel',handle_in,3,
                             [{file,"web/channels/users_channel.ex"},
                              {line,39}]},
                         {'Elixir.Phoenix.Channel.Server',
                             '-handle_info/2-fun-4-',4,
                             [{file,"lib/phoenix/channel/server.ex"},
                              {line,226}]},
                         {gen_server,try_dispatch,4,
                             [{file,"gen_server.erl"},{line,601}]},
                         {gen_server,handle_msg,5,
                             [{file,"gen_server.erl"},{line,667}]},
                         {proc_lib,init_p_do_apply,3,
                             [{file,"proc_lib.erl"},{line,247}]}]}
      in function  gen_server:terminate/7 (gen_server.erl, line 812)
    ancestors: [<0.1734.0>]
    messages: []
    links: [<0.1734.0>,<0.1583.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 6071
  neighbours:
```

**Comment by mitchellhenke** [comment]
What version are you on?  I'm able to get notifications of exceptions within Phoenix channels, so perhaps there is a configuration issue?  Can you gist your configuration?

**Comment by mmartinson** [comment]
I'm not certain that it's the same issue, but my colleague and I were both having issues with RuntimeError reporting as well. Him in a Phoenix channel, and me in a non-phoenix mix application (not behind a plug). I found that the problem was that the logging backend is not being added :error_logger. 

When I run `:error_logger.add_report_handler(Sentry.Logger)` in my Application.start function explicitly the reporting seems to work correctly. Could it be some kind of async race condition with Sentry.start running before Logger.start? I'm not familiar enough with the application start lifecycle to know off the top of my head. I know there were some changes in Elixir 1.4 with how application dependencies are started.

@monicao can you try that snippet and see if yours is the same problem. The code would go here:

```elixir
defmodule YourApp do

  def start(_type, _args) do
    import Supervisor.Spec

    children = []
    opts = [strategy: :one_for_one, name: YouApp.Supervisor]
    Supervisor.start_link(children, opts)

    #here
    :error_logger.add_report_handler(Sentry.Logger)
  end

```

**Comment by monicao** [comment]
@mmartinson Thanks, that totally worked!

@mitchellhenke I am on version 3.0.0. Here is a link to a gist with my config and the controller code I was using to reproduce the issue. It looks like this problem was not restricted to exceptions in phoenix channels.

Let me know if I can provide any additional info.

**Comment by mitchellhenke** [comment]
I was able to reproduce it, but not consistently.  You can check if it's running with:

```elixir
GenEvent.which_handlers(:error_logger)
# => [:error_logger, Logger.ErrorHandler, Sentry.Logger]
```

It seems like it might be related to using Erlang releases/distillery, but I'm not 100% sure.
If you have the time, could you run the code above and confirm that it is indeed not running?  If it's not in the handlers, could you run your application via Mix and check the handlers that way as well?

Depending on the results of the above, it may be the case that we need to move to not trying to set it up within Sentry, and just have users add the report handler within their application.

For now, I'd set `use_error_logger: false`, and do the add_report_handler in your application as above.
