### ISSUE TITLE
Unable to notify Sentry when using Ace web server

### ISSUE THREAD

**Issue by samphilipd** [getsentry/sentry-elixir#195]
I am using the [Ace](https://github.com/CrowdHailer/Ace) webserver. When I get a crash, Sentry fails to report the error.

Here is the full log output:
```
Aug  5 07:40:56 dc1-live-appserver2 elixir[15988]: [error] GenServer #PID<0.1932.0> terminating#012** (MatchError) no match of right hand side value: [nil, nil]#012    (webhooks) lib/webhooks/buyer_requests.ex:71: Webhooks.BuyerRequests.parse_zpg/1#012    (webhooks) lib
Aug  5 07:40:56 dc1-live-appserver2 elixir[15988]: [error] eggl@127.0.0.1 GenServer #PID<0.1932.0> terminating#012** (MatchError) no match of right hand side value: [nil, nil]#012    (webhooks) lib/webhooks/buyer_requests.ex:71: Webhooks.BuyerRequests.parse_zpg/1#012
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]: =CRASH REPORT==== 5-Aug-2017::07:40:56 ===
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:   crasher:
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:     initial call: Elixir.Ace.Server:init/1
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:     pid: <0.1932.0>
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:     registered_name: []
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:     exception error: no match of right hand side value [nil,nil]
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:       in function  'Elixir.Webhooks.BuyerRequests':parse_zpg/1 (lib/webhooks/buyer_requests.ex, line 71)
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:       in call from 'Elixir.Webhooks.BuyerRequests':create_lead/2 (lib/webhooks/buyer_requests.ex, line 11)
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:       in call from 'Elixir.Webhooks.Server':handle_route/4 (lib/webhooks/server.ex, line 16)
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:       in call from 'Elixir.Webhooks.Server':'handle_request (overridable 2)'/2 (lib/webhooks/server.ex, line 1)
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:       in call from 'Elixir.Webhooks.Server':'handle_request (overridable 3)'/2 (lib/webhooks/server.ex, line 1)
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:       in call from 'Elixir.Webhooks.Server':'handle_request (overridable 4)'/2 (lib/webhooks/server.ex, line 1)
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:       in call from 'Elixir.Webhooks.Server':'handle_request (overridable 5)'/2 (lib/tokumei/content_length.ex, line 12)
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:       in call from 'Elixir.Webhooks.Server':handle_request/2 (lib/webhooks/server.ex, line 1)
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:     ancestors: [<0.1927.0>,<0.1926.0>,<0.1925.0>,<0.1924.0>]
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:     message_queue_len: 0
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:     messages: []
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:     links: [<0.1927.0>,#Port<0.5008>]
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:     dictionary: []
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:     trap_exit: false
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:     status: running
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:     heap_size: 2586
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:     stack_size: 27
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:     reductions: 8503
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:   neighbours:
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]: =SUPERVISOR REPORT==== 5-Aug-2017::07:40:56 ===
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:      Supervisor: {<0.1927.0>,'Elixir.Ace.Server.Supervisor'}
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:      Context:    child_terminated
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:      Reason:     {{badmatch,[nil,nil]},
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                   [{'Elixir.Webhooks.BuyerRequests',parse_zpg,1,
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                        [{file,"lib/webhooks/buyer_requests.ex"},{line,71}]},
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                    {'Elixir.Webhooks.BuyerRequests',create_lead,2,
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                        [{file,"lib/webhooks/buyer_requests.ex"},{line,11}]},
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                    {'Elixir.Webhooks.Server',handle_route,4,
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                        [{file,"lib/webhooks/server.ex"},{line,16}]},
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                    {'Elixir.Webhooks.Server',
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                        'handle_request (overridable 2)',2,
Aug  5 07:40:56 dc1-live-appserver2 elixir[15988]: application=sentry [warn] Unable to notify Sentry due to %FunctionClauseError{args: nil, arity: 1, clauses: nil, function: :culprit_from_stacktrace, kind: nil, module: Sentry.Event}! [initial_call: {Ace.Server, :init, [
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                        [{file,"lib/webhooks/server.ex"},{line,1}]},
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                    {'Elixir.Webhooks.Server',
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                        'handle_request (overridable 3)',2,
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                        [{file,"lib/webhooks/server.ex"},{line,1}]},
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                    {'Elixir.Webhooks.Server',
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                        'handle_request (overridable 4)',2,
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                        [{file,"lib/webhooks/server.ex"},{line,1}]},
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                    {'Elixir.Webhooks.Server',
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                        'handle_request (overridable 5)',2,
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                        [{file,"lib/tokumei/content_length.ex"},{line,12}]},
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                    {'Elixir.Webhooks.Server',handle_request,2,
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                        [{file,"lib/webhooks/server.ex"},{line,1}]}]}
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:      Offender:   [{pid,<0.1932.0>},
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                   {id,'Elixir.Ace.Server'},
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                   {mfargs,{'Elixir.Ace.Server',start_link,undefined}},
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                   {restart_type,temporary},
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                   {shutdown,5000},
Aug  5 07:40:56 dc1-live-appserver2 eggl[15947]:                   {child_type,worker}]
Aug  5 07:40:56 dc1-live-appserver2 elixir[15988]: application=sentry [warn] Unable to notify Sentry due to %FunctionClauseError{args: nil, arity: 1, clauses: nil, function: :culprit_from_stacktrace, kind: nil, module: Sentry.Event}! [initial_call: {Ace.Server, :init, [
```

Here is the truncated line:
```
Aug  5 07:40:56 dc1-live-appserver2 elixir[15988]: application=sentry [warn] Unable to notify Sentry due to %FunctionClauseError{args: nil, arity: 1, clauses: nil, function: :culprit_from_stacktrace, kind: nil, module: Sentry.Event}! [initial_call: {Ace.Server, :init, [:Argument__1]}, pid: #PID<0.1932.0>, registered_name: [], error_info: {:error, {:badmatch, [nil, nil]}, [{Webhooks.BuyerRequests, :parse_zpg, 1, [file: 'lib/webhooks/buyer_requests.ex', line: 71]}, {Webhooks.BuyerRequests, :create_lead, 2, [file: 'lib/webhooks/buyer_requests.ex', line: 11]}, {Webhooks.Server, :handle_route, 4, [file: 'lib/webhooks/server.ex', line: 16]}, {Webhooks.Server, :"handle_request (overridable 2)", 2, [file: 'lib/webhooks/server.ex', line: 1]}, {Webhooks.Server, :"handle_request (overridable 3)", 2, [file: 'lib/webhooks/server.ex', line: 1]}, {Webhooks.Server, :"handle_request (overridable 4)", 2, [file: 'lib/webhooks/server.ex', line: 1]}, {Webhooks.Server, :"handle_request (overridable 5)", 2, [file: 'lib/tokumei/content_length.ex', line: 12]}, {Webhooks.Server, :handle_request, 2, [file: 'lib/webhooks/server.ex', line: 1]}]}, ancestors: [#PID<0.1927.0>, #PID<0.1926.0>, #PID<0.1925.0>, #PID<0.1924.0>], message_queue_len: 0, messages: [], links: [#PID<0.1927.0>, #Port<0.5008>], dictionary: [], trap_exit: false, status: :running, heap_size: 2586, stack_size: 27, reductions: 8503]
```

**Comment by mitchellhenke** [comment]
@samphilipd thanks for opening this!  I should be able to fix this shortly.

**Comment by samphilipd** [comment]
@mitchellhenke great, thanks! Let me know if you need any more info, code samples etc.

**Comment by mitchellhenke** [comment]
@samphilipd I'm having an issue reproducing this.  If possible, could you put together an example?

**Comment by samphilipd** [comment]
@mitchellhenke what version of Ace are you trying with? I'm on 0.9.3

**Comment by mitchellhenke** [comment]
@samphilipd I was on master, and used the example app provided in the Ace repository.

**Comment by samphilipd** [comment]
Oh! I just checked and it must have been fixed. Because it seems to be working now.

I guess this issue can be closed.

**Comment by mitchellhenke** [comment]
@samphilipd cool, glad to hear!  Thanks again for taking the time to open an issue.
