### ISSUE TITLE
Sentry swallows errors in test environment

### ISSUE THREAD

**Issue by matthewlehner** [getsentry/sentry-elixir#264]
### Environment

* Elixir version (elixir -v): 1.6.4
* Erlang/OTP version (erl): 20.3.2
* Sentry version (mix deps): 6.2.0
* Operating system: MacOS

### Description
Adding `Sentry.Plug` behaviour to the router creates a stack trace that obfuscates where the real errors are being thrown.

### Expected Behavior
The stack traces that are thrown during tests should not be swallowed by Sentry.

```
     ** (Ecto.Query.CastError) lib/TestApp/analytics/analytics.ex:149: value `%TestApp.Analytics.App{__meta__: #Ecto.Schema.Metadata<:loaded, "apps">, created_at: ~N[2018-04-14 16:49:52.332741], id: 2129, identifier: "st", title: "Sentry Test", updated_at: ~N[2018-04-14 16:49:52.332752]}` in `where` cannot be cast to type :id in query:

     from a in TestApp.Analytics.Report,
       where: a.app_id == ^%TestApp.Analytics.App{__meta__: #Ecto.Schema.Metadata<:loaded, "apps">, created_at: ~N[2018-04-14 16:49:52.332741], id: 2129, identifier: "st", title: "Sentry Test", updated_at: ~N[2018-04-14 16:49:52.332752]} and a.report_date >= ^~D[2018-04-13] and a.report_date <= ^~D[2018-04-14],
       select: a

    stacktrace:
       (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
       (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/repo/queryable.ex:124: Ecto.Repo.Queryable.execute/5
       (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
       (test_app) lib/test_app_web/controllers/report_controller.ex:61: TestAppWeb.ReportController.index/2
       (test_app) lib/test_app_web/controllers/report_controller.ex:1: TestAppWeb.ReportController.action/2
       (test_app) lib/test_app_web/controllers/report_controller.ex:1: TestAppWeb.ReportController.phoenix_controller_pipeline/2
       (test_app) lib/test_app_web/endpoint.ex:1: TestAppWeb.Endpoint.instrument/4
       (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
       (test_app) lib/plug/error_handler.ex:64: TestAppWeb.Router.call/2
```

### Actual Behavior
```
     ** (FunctionClauseError) no function clause matching in URI.parse/1

     The following arguments were given to URI.parse/1:

         # 1
         nil

     Attempted function clauses (showing 2 out of 2):

         def parse(%URI{} = uri)
         def parse(string) when is_binary(string)

     code: |> get(report_path(conn, :index, params), nil)
     stacktrace:
       (elixir) lib/uri.ex:414: URI.parse/1
       (sentry) lib/sentry/client.ex:213: Sentry.Client.get_dsn/0
       (sentry) lib/sentry/client.ex:308: Sentry.Client.get_headers_and_endpoint/0
       (sentry) lib/sentry/client.ex:88: Sentry.Client.do_send_event/3
       (test_app) lib/test_app_web/endpoint.ex:1: TestAppWeb.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/test_app_web/controllers/report_controller_test.exs:27: (test)
```

### Steps to Reproduce
Write a controller (`ConnCase`) test that throws an exception with Sentry configured as per the documentation – `Sentry.Plug` to the router, and `Sentry.Phoenix.Endpoint` to the Phoenix endpoint module.

**Comment by mitchellhenke** [comment]
Thanks for opening the issue! It looks like you have Sentry configured to run in the test environment, and it's failing while trying to send an error because the DSN is not configured and is trying to parse `nil`.

If you don't want to be running Sentry in the test environment, see the `:environment_name` and `:included_environments` configuration documentation in https://hexdocs.pm/sentry/readme.html#configuration.

**Comment by mitchellhenke** [comment]
If there's further information, I can reopen this, but I am going to close it for now :)
