### ISSUE TITLE
elixir 1.15: "The log level `:warn` is deprecated, use `:warning` instead"

### ISSUE THREAD

**Issue by NobbZ** [getsentry/sentry-elixir#561]
### Environment

* Elixir 1.15.x
* sentry 8.0.6
* OTP 26

### Steps to Reproduce

1. Use sentry, it seems as if already starting the application causes the warning to appear

### Expected Result

No warning will be logged

### Actual Result

A deprecation warning is issued:

```text
warning: the log level :warn is deprecated, use :warning instead
  (logger 1.15.3) lib/logger.ex:1137: Logger.elixir_level_to_erlang_level/1
  (logger 1.15.3) lib/logger.ex:591: Logger.compare_levels/2
  (sentry 8.0.6) lib/sentry/logger_backend.ex:73: Sentry.LoggerBackend.handle_event/2
  (stdlib 5.0.2) gen_event.erl:802: :gen_event.server_update/4
  (stdlib 5.0.2) gen_event.erl:784: :gen_event.server_notify/4
  (stdlib 5.0.2) gen_event.erl:526: :gen_event.handle_msg/6
  (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

**Comment by whatyouhide** [comment]
This is fixed in the `master` branch, we're working on a release.

**Comment by andersonvom** [comment]
@whatyouhide do you have a sense of when the next release will be available?
