### ISSUE TITLE
Errors are unreadable in v9 and v10

### ISSUE THREAD

**Issue by anthonator** [getsentry/sentry-elixir#685]
### Environment

Elixir 1.14.5
Erlang 25.3.2.7
Sentry 10.1.0

### Steps to Reproduce

Configured Sentry according to documentation on HexDocs.

**Our config**

```
if config_env() == :prod do
  config :sentry,
    dsn: System.fetch_env!("SENTRY_DSN"),
    enable_source_code_context: true,
    environment_name: System.fetch_env!("SENTRY_ENV"),
    hackney_opts: [
      ssl_options: [
        cacertfile: :certifi.cacertfile()
      ]
    ],
    root_source_code_paths: [File.cwd!()]
end
```

### Expected Result

Errors would continue coming into Sentry in a readable format.

### Actual Result

<img width="908" alt="Screenshot 2024-01-31 at 4 42 16 PM" src="https://github.com/getsentry/sentry-elixir/assets/420061/62b3ccaa-29be-4e73-a649-9fd4afe7578b">

**Comment by whatyouhide** [comment]
Hi @anthonator, thanks for the report. I'd need a bit more info in order to debug this.

1. What's the error that you're seeing in the logs, that gets reported as the screenshot above?
1. Is your Sentry project configured as an Elixir project (on Sentry)?
1. Do you have a way to reproduce this with a minimal Elixir app?

**Comment by anthonator** [comment]
Thanks for getting back to me!

> What's the error that you're seeing in the logs, that gets reported as the screenshot above?

```
2024-02-06 11:32:19.831** (exit) an exception was raised: | 2024-02-06 11:32:19.831 | ** (exit) an exception was raised: |  
-- | -- | -- | --
2024-02-06 11:32:19.831 | ** (exit) an exception was raised: |  

2024-02-06 11:32:19.831    ** (Ecto.ConstraintError) constraint error when attempting to insert struct: |   |   | 2024-02-06 11:32:19.831 | ** (Ecto.ConstraintError) constraint error when attempting to insert struct: |  
  |   | 2024-02-06 11:32:19.831 | ** (Ecto.ConstraintError) constraint error when attempting to insert struct: |  
2024-02-06 11:32:19.8312024-02-06 11:32:19.831    * "***_index" (unique_constraint)2024-02-06 11:32:19.8312024-02-06 11:32:19.831If you would like to stop this constraint violation from raising an2024-02-06 11:32:19.831exception and instead add it as an error to your changeset, please2024-02-06 11:32:19.831call `unique_constraint/3` on your changeset with the constraint2024-02-06 11:32:19.831`:name` as an option.2024-02-06 11:32:19.8312024-02-06 11:32:19.831The changeset defined the following constraints:2024-02-06 11:32:19.8312024-02-06 11:32:19.831    * "***_index" (unique_constraint)2024-02-06 11:32:19.8312024-02-06 11:32:19.831        (ecto 3.10.3) lib/ecto/repo/schema.ex:804: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/32024-02-06 11:32:19.831        (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/22024-02-06 11:32:19.831        (ecto 3.10.3) lib/ecto/repo/schema.ex:788: Ecto.Repo.Schema.constraints_to_errors/32024-02-06 11:32:19.831        (ecto 3.10.3) lib/ecto/repo/schema.ex:769: Ecto.Repo.Schema.apply/42024-02-06 11:32:19.831        (ecto 3.10.3) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/42024-02-06 11:32:19.831        (ecto 3.10.3) lib/ecto/multi.ex:844: Ecto.Multi.apply_operation/52024-02-06 11:32:19.831        (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/32024-02-06 11:32:19.831        (ecto 3.10.3) lib/ecto/multi.ex:818: anonymous fn/5 in Ecto.Multi.apply_operations/5 |   |   | 2024-02-06 11:32:19.831 |   |   |   |   | 2024-02-06 11:32:19.831 | * "***_index" (unique_constraint) |   |   |   | 2024-02-06 11:32:19.831 |   |   |   |   | 2024-02-06 11:32:19.831 | If you would like to stop this constraint violation from raising an |   |   |   | 2024-02-06 11:32:19.831 | exception and instead add it as an error to your changeset, please |   |   |   | 2024-02-06 11:32:19.831 | call `unique_constraint/3` on your changeset with the constraint |   |   |   | 2024-02-06 11:32:19.831 | `:name` as an option. |   |   |   | 2024-02-06 11:32:19.831 |   |   |   |   | 2024-02-06 11:32:19.831 | The changeset defined the following constraints: |   |   |   | 2024-02-06 11:32:19.831 |   |   |   |   | 2024-02-06 11:32:19.831 | * "***_index" (unique_constraint) |   |   |   | 2024-02-06 11:32:19.831 |   |   |   |   | 2024-02-06 11:32:19.831 | (ecto 3.10.3) lib/ecto/repo/schema.ex:804: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3 |   |   |   | 2024-02-06 11:32:19.831 | (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2 |   |   |   | 2024-02-06 11:32:19.831 | (ecto 3.10.3) lib/ecto/repo/schema.ex:788: Ecto.Repo.Schema.constraints_to_errors/3 |   |   |   | 2024-02-06 11:32:19.831 | (ecto 3.10.3) lib/ecto/repo/schema.ex:769: Ecto.Repo.Schema.apply/4 |   |   |   | 2024-02-06 11:32:19.831 | (ecto 3.10.3) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4 |   |   |   | 2024-02-06 11:32:19.831 | (ecto 3.10.3) lib/ecto/multi.ex:844: Ecto.Multi.apply_operation/5 |   |   |   | 2024-02-06 11:32:19.831 | (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3 |   |   |   | 2024-02-06 11:32:19.831 | (ecto 3.10.3) lib/ecto/multi.ex:818: anonymous fn/5 in Ecto.Multi.apply_operations/5
  |   | 2024-02-06 11:32:19.831 |   |  
  |   | 2024-02-06 11:32:19.831 | * "***_index" (unique_constraint) |  
  |   | 2024-02-06 11:32:19.831 |   |  
  |   | 2024-02-06 11:32:19.831 | If you would like to stop this constraint violation from raising an |  
  |   | 2024-02-06 11:32:19.831 | exception and instead add it as an error to your changeset, please |  
  |   | 2024-02-06 11:32:19.831 | call `unique_constraint/3` on your changeset with the constraint |  
  |   | 2024-02-06 11:32:19.831 | `:name` as an option. |  
  |   | 2024-02-06 11:32:19.831 |   |  
  |   | 2024-02-06 11:32:19.831 | The changeset defined the following constraints: |  
  |   | 2024-02-06 11:32:19.831 |   |  
  |   | 2024-02-06 11:32:19.831 | * "***_index" (unique_constraint) |  
  |   | 2024-02-06 11:32:19.831 |   |  
  |   | 2024-02-06 11:32:19.831 | (ecto 3.10.3) lib/ecto/repo/schema.ex:804: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3 |  
  |   | 2024-02-06 11:32:19.831 | (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2 |  
  |   | 2024-02-06 11:32:19.831 | (ecto 3.10.3) lib/ecto/repo/schema.ex:788: Ecto.Repo.Schema.constraints_to_errors/3 |  
  |   | 2024-02-06 11:32:19.831 | (ecto 3.10.3) lib/ecto/repo/schema.ex:769: Ecto.Repo.Schema.apply/4 |  
  |   | 2024-02-06 11:32:19.831 | (ecto 3.10.3) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4 |  
  |   | 2024-02-06 11:32:19.831 | (ecto 3.10.3) lib/ecto/multi.ex:844: Ecto.Multi.apply_operation/5 |  
  |   | 2024-02-06 11:32:19.831 | (elixir 1.14.5) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3 |  
  |   | 2024-02-06 11:32:19.831 | (ecto 3.10.3) lib/ecto/multi.ex:818: anonymous fn/5 in Ecto.Multi.apply_operations/5
```
> Is your Sentry project configured as an Elixir project (on Sentry)?

No, it is not. Although this hasn't been an issue for projects using v8.

> Do you have a way to reproduce this with a minimal Elixir app?

No, not currently

**Comment by whatyouhide** [comment]
> No, it is not. Although this hasn't been an issue for projects using v8.

If you change the project type to Elixir, does that change anything?

> No, not currently

It's really hard for me to help debug this without any way to reproduce it 😢. All my tests point to errors showing up correctly, and we're on 10.1.0 at work and errors also show up correctly (also with Cowboy + Phoenix).

**Comment by anthonator** [comment]
I recently upgraded another project to v10.1.0 and we're seeing the same issue. The Sentry project for this application is set as Elixir. Everything worked perfectly using v8.x.

If I have time I'll try to put together a minimal reproduction app.

Here are some additional details.

This is the first line of `start/2` in our `Application` module:

```
:logger.add_handler(:sentry_handler, Sentry.LoggerHandler, %{})
```

We also removed all use of `Sentry.LoggerBackend`.

This is the first line of our endpont:

```
use Sentry.PlugCapture
```

The `runtime.exs` looks like this.

```
if config_env() == :prod do
  config :sentry,
    dsn: System.get_env("SENTRY_DSN"),
    enable_source_code_context: true,
    environment_name: System.get_env("SENTRY_ENV"),
    hackney_opts: [
      ssl_options: [
        cacertfile: :certifi.cacertfile(),
        customize_hostname_check: [match_fun: :public_key.pkix_verify_hostname_match_fun(:https)],
        verify: :verify_peer,
        verify_fun: &:ssl_verify_hostname.verify_fun/3,
        versions: [:"tlsv1.2", :"tlsv1.3"]
      ]
    ],
    root_source_code_paths: [File.cwd!()]
end
```

This is how we create the release in our `Dockerfile`:

```
RUN apk upgrade --no-cache \
    && mix deps.get \
    && mix compile \
    && mix app.config \
    && mix sentry.package_source_code \
    && mix release
```

Here's another example of what we're seeing in Sentry.

<img width="1187" alt="Screenshot 2024-02-08 at 11 23 41 AM" src="https://github.com/getsentry/sentry-elixir/assets/420061/2c66e329-e721-4c99-8d07-54d25002efec">

**Comment by anthonator** [comment]
Just tried moving some Sentry config to `config.exs` to see if there's a problem with the source mapping. Still seeing the same issue.

`config.exs`
```
config :sentry,
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()]
```

`runtime.exs`
```
if config_env() == :prod do
  config :sentry,
    dsn: System.get_env("SENTRY_DSN"),
    environment_name: System.get_env("SENTRY_ENV"),
    hackney_opts: [
      ssl_options: [
        cacertfile: :certifi.cacertfile(),
        customize_hostname_check: [match_fun: :public_key.pkix_verify_hostname_match_fun(:https)],
        verify: :verify_peer,
        verify_fun: &:ssl_verify_hostname.verify_fun/3,
        versions: [:"tlsv1.2", :"tlsv1.3"]
      ]
    ]
end
```

When I run `MIX_ENV=prod mix sentry.package_source_code`, I see:

```
Wrote 207 files in 139.6 kb to: _build/prod/lib/sentry/priv/sentry.map
```

When I make a release I can see `sentry.map` in `_build/prod/rel/myapp/lib/sentry-10.1.0/priv`.

**Comment by anthonator** [comment]
When I call `Sentry.Sources.get_source_code_map_from_persistent_term()` I don't see any maps for anything outside of my projects `lib/` directory. So no dependencies. The errors I'm seeing that have this issue seem to be coming from dependencies.

Not sure if this is relevant but thought I'd share.

**Comment by anthonator** [comment]
Tried removing `deps/` from the exclude list with `source_code_exclude_patterns: [~r/\/_build\//, ~r/\/priv\//, ~r/\/test\//]`.

I could see that more files were being added to the source map but still the same result.

**Comment by anthonator** [comment]
I don't have a good 1-to-1 but here is another error that we see the issue with in 10.1.0. After downgrading to 8.1.0 this is what we see.

<img width="1182" alt="Screenshot 2024-02-08 at 4 19 51 PM" src="https://github.com/getsentry/sentry-elixir/assets/420061/46c6013d-7983-4267-bf40-61baad1337d1">

**Comment by whatyouhide** [comment]
@anthonator did you have a chance to get a reproduceable example? Also, we did some changes in the `:logger` handler, so might be worth trying out 10.4.0.

For now, I will close this as I have no way to reproduce this, but we can reopen if anything pops up.

**Comment by anthonator** [comment]
I have not been able to get a reproducible example together, unfortunately. However, this is still an issue for us. Only thing we’ve been able to do is downgrade to 8.x. All versions 9+ have exhibited this behavior.

Thanks for helping where you could on this.

**Comment by mhsdef** [comment]
We're seeing the same thing in trying to go from `8.x` -> `10.x`.

Here's our logger config now with `10.8.1`:

```
   :logger.add_handler(:sentry_handler, Sentry.LoggerHandler, %{
      config: %{metadata: [:file, :line]}
    })
```

Here's a sample:

```
%{label: {:supervisor, :child_terminated}, report: [supervisor: {#PID<0.9613.0>, Supervisor.Default}, errorContext: :child_terminated, reason: {%RuntimeError{message: "Pubsub not configured!\n\nSubscriptions require a configured pubsub module.\n"}, [{Absinthe.Phase.Subscription.SubscribeSelf, :ensure_pubsub!, 1, [file: 'lib/absinthe/phase/subscription/subscribe_self.ex', line: 109, error_info: %{module: Exception}]}, {Absinthe.Phase.Subscription.SubscribeSelf, :do_subscription, 3, [file: 'lib/absinthe/phase/subscription/subscribe_self.ex', line: 20]}, {Absinthe.Pipeline, :run_phase, 3, [file: 'lib/absinthe/pipeline.ex', line: 370]}, {Absinthe.Phoenix.Channel, :run, 4, [file: 'lib/absinthe/phoenix/channel.ex', line: 123]}, {Absinthe.Phoenix.Channel, :run_doc, 4, [file: 'lib/absinthe/phoenix/channel.ex', line: 91]}, {Absinthe.Phoenix.Channel, :handle_in, 3, [file: 'lib/absinthe/phoenix/channel.ex', line: 57]}, {Phoenix.Channel.Server, :handle_info, 2, [file: 'lib/phoenix/channel/server.ex', line: 322]}, {:gen_server, :try_handle_info, 3, [file: 'gen_server.erl', line: 1095]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 1183]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 241]}]}, offender: [pid: #PID<0.96241.0>, id: :undefined, mfargs: {Absinthe.Phoenix.Channel, :start_link, :undefined}, restart_type: :temporary, shutdown: 5000, child_type: :worker]]}
```

<img width="870" alt="Image" src="https://github.com/user-attachments/assets/376296fd-7a3e-468c-9718-0fd40fe8bbb1" />

Previously, with `8.x`, it was purdy. 😢 

Here was our logger config:

```
    Logger.add_backend(Sentry.LoggerBackend)
```

<img width="877" alt="Image" src="https://github.com/user-attachments/assets/d51037a1-8f39-4cb7-9fe0-9b2487d53db2" />

**Comment by solnic** [comment]
@mhsdef this is addressed via https://github.com/getsentry/sentry-elixir/pull/851 :)
