### ISSUE TITLE
App output obscured by continual deprecation warning "the log level :warn is deprecated, use :warning instead"

### ISSUE THREAD

**Issue by FreedomBen** [getsentry/sentry-elixir#693]
## App output obscured by continual deprecation warning "the log level :warn is deprecated, use :warning instead"

When running the app, on every request I get a dozen or more deprecation warnings like this:

`warning: the log level :warn is deprecated, use :warning instead`

The stack trace indicates that it comes from the Sentry logger backend.  That's the only part of this that comes from the app:

```
warning: the log level :warn is deprecated, use :warning instead                                                      
  (logger 1.15.4) lib/logger.ex:1137: Logger.elixir_level_to_erlang_level/1                                           
  (logger 1.15.4) lib/logger.ex:592: Logger.compare_levels/2                                                          
  (sentry 10.1.0) lib/sentry/logger_backend.ex:94: Sentry.LoggerBackend.handle_event/2                                
  (stdlib 4.3.1.2) gen_event.erl:802: :gen_event.server_update/4                                                      
  (stdlib 4.3.1.2) gen_event.erl:784: :gen_event.server_notify/4                                                      
  (stdlib 4.3.1.2) gen_event.erl:526: :gen_event.handle_msg/6                                                         
  (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

I looked through the codebase and I can't find anywhere that it calls `warn` instead of `warning`.  In fact I found code that seems to intentionally make sure it calls `warning`.  This makes me think maybe my app is invoking the sentry package incorrectly, but I reviewed every occurence and it never specifies any log level.  I've run a `mix deps.clean` to ensure I'm not inadvertently running an older version.

### Environment

Phoenix v1.6.16 app on Elixir v1.15.4 Erlang v25

Version 10.1.  More specifically from `mix.lock`:

```
"sentry": {:hex, :sentry, "10.1.0", "5d73c23deb5d95f3027fbb09801bd8e787065be61f0065418aed3961becbbe9f", [:mix], [{:hackney, "~> 1.8", [hex: :hackney, repo: "hexpm", optional: true]}, {:jason, "~> 1.1", [hex: :jason, repo: "hexpm", optio
nal: true]}, {:nimble_options, "~> 1.0", [hex: :nimble_options, repo: "hexpm", optional: false]}, {:plug, "~> 1.6", [hex: :plug, repo: "hexpm", optional: true]}, {:plug_cowboy, "~> 2.3", [hex: :plug_cowboy, repo: "hexpm", optional: true]}
], "hexpm", "f4319e7491133046912b4cf7cbe6f5226b309275d1a6d05386cce2ac7f97b2d2"},
```

### Steps to Reproduce

1. Run the app.
2. Upgrade to the latest hex package (10.1 right now)
3. Run the app again.  Observe the deprecation warnings are still present

### Expected Result

No deprecation warnings

### Actual Result

Lots of deprecation warnings like this:

```
warning: the log level :warn is deprecated, use :warning instead                                                      
  (logger 1.15.4) lib/logger.ex:1137: Logger.elixir_level_to_erlang_level/1                                           
  (logger 1.15.4) lib/logger.ex:592: Logger.compare_levels/2                                                          
  (sentry 10.1.0) lib/sentry/logger_backend.ex:94: Sentry.LoggerBackend.handle_event/2                                
  (stdlib 4.3.1.2) gen_event.erl:802: :gen_event.server_update/4                                                      
  (stdlib 4.3.1.2) gen_event.erl:784: :gen_event.server_notify/4                                                      
  (stdlib 4.3.1.2) gen_event.erl:526: :gen_event.handle_msg/6                                                         
  (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by FreedomBen** [comment]
I had this feeling when I opened this, that _somehow_ it was user error.  True enough it was.  I found this in `config/config.exs` and sure enough this was the cause:

```elixir
config :logger, Sentry.LoggerBackend,
  level: :warn,  # Change this to :warning !
  excluded_domains: [],
  capture_log_messages: true
```

Leaving this issue up in case it's helpful to someone else, but there's no bug here.
