### ISSUE TITLE
Could not fetch application environment `:sender_pool_size`

### ISSUE THREAD

**Issue by h3poteto** [getsentry/sentry-elixir#709]
### Environment

- OTP  25.3
- Elixir 1.13.4
- sentry-elixir 10.3.0

### Steps to Reproduce

I'm sorry, but I cannot reproduce it 100%.
I'm using sentry-elixir with a Phoenix application, and usually, it works fine. Exceptions are reported to Sentry.

But, sometimes sentry-elixir says an error after an exception.

### Expected Result

An exception log is sent to Sentry without errors.

### Actual Result

After an exception happens

```
09:26:13.789 [error] :gen_event handler Sentry.LoggerBackend installed in Logger terminating
** (ArgumentError) could not fetch application environment :sender_pool_size for application :sentry because configuration at :sender_pool_size was not set
(elixir 1.13.4) lib/application.ex:683: Application.fetch_env!/2
(sentry 10.3.0) lib/sentry/transport/sender.ex:22: Sentry.Transport.Sender.send_async/2
(sentry 10.3.0) lib/sentry/client.ex:241: Sentry.Client.encode_and_send/4
(sentry 10.3.0) lib/sentry/client.ex:124: Sentry.Client.send_event/2
(sentry 10.3.0) lib/sentry/logger_backend.ex:96: Sentry.LoggerBackend.handle_event/2
(stdlib 4.3) gen_event.erl:802: :gen_event.server_update/4
(stdlib 4.3) gen_event.erl:784: :gen_event.server_notify/4
(stdlib 4.3) gen_event.erl:526: :gen_event.handle_msg/6
```

It doesn't always occur. Occasionally occurs, and at this time, the error is not sent to Sentry.

**Comment by h3poteto** [comment]
Thank you!
