### ISSUE TITLE
`Sentry.Config.dsn/0` is not a string.

### ISSUE THREAD

**Issue by maennchen** [getsentry/sentry-elixir#730]
### Environment

10.5.0

### Steps to Reproduce

* Following the [Capturing User Feedback](https://docs.sentry.io/platforms/elixir/integrations/plug_and_phoenix/#capturing-user-feedback) Guide
* Calls `Sentry.Config.dsn()`

The integration was originally added with major version 8 and worked great. After the update to version 10, the dsn is no longer a string.

Back in version 8, the module `Sentry.Config` was public. Now it is marked with `@moduledoc false`.

### Expected Result

Works and only uses public APIs.

Alternatively, the docs should provide an alternative to achieve the same result.

### Actual Result

```
14:32:56.317 [error] #PID<0.708.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.707.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /url
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for {"https://[...].ingest.us.sentry.io/api/[...]/envelope/", "[...]", nil} of type Tuple. This protocol is implemented for the following type(s): Atom, BitString, Date, DateTime, Decimal, Float, Integer, List, NaiveDateTime, Phoenix.LiveComponent.CID, Phoenix.LiveView.Component, Phoenix.LiveView.Comprehension, Phoenix.LiveView.JS, Phoenix.LiveView.Rendered, Time, Tuple, URI
        (phoenix_html 4.1.1) lib/phoenix_html/safe.ex:97: Phoenix.HTML.Safe.Tuple.to_iodata/1
        (phoenix_html 4.1.1) lib/phoenix_html.ex:238: Phoenix.HTML.build_attrs/1
        (phoenix_html 4.1.1) lib/phoenix_html.ex:191: Phoenix.HTML.attributes_escape/1
        (acme 1.0.0) lib/athena_web/components/layouts/root.html.heex:2: anonymous fn/2 in AcmeWeb.Layouts.root/1
```

Using API marked as `@moduledoc false`.

**Comment by whatyouhide** [comment]
Good catch. Will be released in the next minor version,
