### ISSUE TITLE
GenServer {Sentry.Transport.SenderRegistry, 6} terminating

### ISSUE THREAD

**Issue by rlopzc** [getsentry/sentry-elixir#786]
### Environment

What version are you running?
10.7.1

### Steps to Reproduce

1. Integrate sentry and run the server
2. I purposely didn't turn on the DB to see the errors in the dashboard to test the integration
3. Failed

### Expected Result

See all errors reported to sentry. Just got one randomly, not sure how 🤷 .

### Actual Result

```
[error] Postgrex.Protocol (#PID<0.472.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (REDACTED): connection refused - :econnrefused
[info] [message: "notifier only receiving messages from its own node, functionality may be degraded", source: "oban", event: "notifier:switch", connectivity_status: :solitary]
[error] GenServer {Sentry.Transport.SenderRegistry, 6} terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, Phoenix.LiveView.LiveStream, Postgrex.Stream, Range, Req.Response.Async, Stream, Timex.Interval
    (elixir 1.17.2) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.17.2) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.17.2) lib/enum.ex:4423: Enum.map/2
    (sentry 10.7.1) lib/sentry/client.ex:292: anonymous fn/1 in Sentry.Client.render_exception/1
    (sentry 10.7.1) lib/sentry/client.ex:360: Sentry.Client.update_if_present/3
    (elixir 1.17.2) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (sentry 10.7.1) lib/sentry/client.ex:360: Sentry.Client.update_if_present/3
    (sentry 10.7.1) lib/sentry/client.ex:283: Sentry.Client.render_event/1
    (sentry 10.7.1) lib/sentry/envelope.ex:61: Sentry.Envelope.item_to_binary/2
    (elixir 1.17.2) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (sentry 10.7.1) lib/sentry/envelope.ex:53: Sentry.Envelope.to_binary/1
    (sentry 10.7.1) lib/sentry/transport.ex:23: Sentry.Transport.post_envelope/3
    (sentry 10.7.1) lib/sentry/transport/sender.ex:46: Sentry.Transport.Sender.handle_cast/2
    (stdlib 6.0.1) gen_server.erl:2199: :gen_server.try_handle_cast/3
    (stdlib 6.0.1) gen_server.erl:2261: :gen_server.handle_msg/6
    (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Process Label: Sentry.Transport.Sender
Last message: {:"$gen_cast", {:send, Sentry.HackneyClient, %Sentry.Event{event_id: "0569d2eb222249aebc750a1fc8368031", timestamp: "2024-09-05T22:34:09.632321", breadcrumbs: [], contexts: %{runtime: %{name: "elixir", version: "1.17.2 (compiled with Erlang/OTP 27)"}, os: %{name: "linux", version: "6.6.49"}}, dist: nil, environment: "dev", exception: [%Sentry.Interfaces.Exception{type: "DBConnection.ConnectionError", value: "tcp connect (REDACTED): connection refused - :econnrefused", module: nil, stacktrace: %Sentry.Interfaces.Stacktrace{frames: nil}, mechanism: %Sentry.Interfaces.Exception.Mechanism{handled: false, data: nil, synthetic: nil, help_link: nil, meta: nil, type: "generic"}}], extra: %{domain: [:elixir], logger_level: :error, logger_metadata: %{line: 107, file: "lib/db_connection/connection.ex"}}, fingerprint: ["{{ default }}"], level: :error, logger: nil, message: nil, modules: %{"bcrypt_elixir" => "3.1.0", "iex" => "1.17.2", "esbuild" => "0.8.1", "rustler_precompiled" => "0.8.0", "hpack" => "0.3.0", "castore" => "1.0.8", "mint" => "1.6.2", "ssl_verify_fun" => "1.1.7", "gproc" => "0.9.1", "idna" => "6.1.1", "comeonin" => "5.4.0", "phoenix_template" => "1.0.4", "merge_pdf" => "0.4.0", "plug_crypto" => "2.1.0", "jason" => "1.4.4", "dialyxir" => "1.4.3", "opentelemetry_ecto" => "1.2.0", "dns_cluster" => "0.1.3", "phoenix_html_helpers" => "1.0.1", "eex" => "1.17.2", "ex_cldr_dates_times" => "2.20.3", "oban_met" => "0.1.7", "ex_cldr_calendars" => "1.26.1", "joken" => "2.6.2", "configparser_ex" => "4.0.0", "decorator" => "1.4.0", "gettext" => "0.26.1", "jose" => "1.11.10", "ranch" => "1.8.0", "phoenix_live_view" => "1.0.0-rc.6", "makeup" => "1.1.2", "cowboy" => "2.12.0", ...}, platform: :elixir, release: "0.0.1", request: %Sentry.Interfaces.Request{method: nil, url: nil, query_string: nil, data: nil, cookies: nil, headers: nil, env: nil}, sdk: %Sentry.Interfaces.SDK{name: "sentry-elixir", version: "10.7.1"}, server_name: "matrix", tags: %{}, transaction: nil, threads: nil, user: %{}, integration_meta: %{}, culprit: nil, attachments: [], source: :logger, original_exception: %DBConnection.ConnectionError{message: "tcp connect (REDACTED): connection refused - :econnrefused", severity: :error, reason: :error}}}}
```

**Comment by rlopzc** [comment]
So, events are deduped every 10 secs (just read the code), but the error I posted is still raised whenever I turn on/off the DB.

**Comment by savhappy** [comment]
@rlopzc can you provide more info? The error posted is expected if the DB connection fails and should be reported. Are you saying you expect to see more errors in the dashboard beyond this one?

**Comment by whatyouhide** [comment]
@savhappy this part of the error comes from Sentry, and it shouldn't

**Comment by savhappy** [comment]
Ah I see! It seems like this is originating from frames being set to nil.

**Comment by savhappy** [comment]
[PR ](https://github.com/getsentry/sentry-elixir/pull/787) out for review. Thank you for the catch @rlopzc 💟

**Comment by axelson** [comment]
Was this introduced in a recent release? i.e. could we avoid this by rolling back to Sentry 10.6.2 until this fix is released?

**Comment by savhappy** [comment]
@axelson the changes were introduced in 10.7 so yes you could rollback and wouldn't see this error. Although, you might encounter the error mentioned in issue #770 that this code was a fix for.

**Comment by axelson** [comment]
Okay, thanks I'll downgrade for now since this bug has caused our server to crash resulting in a small amount of downtime as the server was restarted. Thanks for the confirmation 👍
