### ISSUE TITLE
Getting undefined function String.trim/2

### ISSUE THREAD

**Issue by shawnbro** [getsentry/sentry-elixir#95]
When an exception is raised in my Phoenix app, nothing is reported to sentry.  here is the log output:

```
** (exit) an exception was raised:
2016-12-01T23:14:00.741733+00:00 app[web.1]:     ** (UndefinedFunctionError) undefined function String.trim/2
2016-12-01T23:14:00.741736+00:00 app[web.1]:         (elixir) String.trim("** (Phoenix.ActionClauseError) bad request to MyApp.UserController.create, no matching action clause to process request", "*")
2016-12-01T23:14:00.741737+00:00 app[web.1]:         (sentry) lib/sentry/event.ex:65: Sentry.Event.transform_exception/2
2016-12-01T23:14:00.741738+00:00 app[web.1]:         (sentry) lib/sentry.ex:86: Sentry.capture_exception/2
2016-12-01T23:14:00.741739+00:00 app[web.1]:         (plug) lib/plug/error_handler.ex:96: Plug.ErrorHandler.__catch__/5
2016-12-01T23:14:00.741740+00:00 app[web.1]:         (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.phoenix_pipeline/1
2016-12-01T23:14:00.741741+00:00 app[web.1]:         (my_app) lib/my_app/endpoint.ex:1: MyApp.Endpoint.call/2
2016-12-01T23:14:00.741742+00:00 app[web.1]:         (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
2016-12-01T23:14:00.741742+00:00 app[web.1]:         (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

Any suggestions?

UPDATE
for some reason the `String` module is not defined in production when deployed to Heroku

**Comment by Mazyod** [comment]
Hey @shawnbro,

I pulled a docker image of elixir:1.2.6, and it seems `String.trim` functions were not introduced then.
Try creating `elixir_buildpack.config` file and setting your Elixir version to +1.3.x:

```
erlang_version=19.0
elixir_version=1.3.4
```

**Comment by mitchellhenke** [comment]
thanks @Mazyod, that is correct.  🙂 

Sentry Elixir only supports Elixir versions 1.3 or higher.  While `String.trim/2` did exist in 1.2, it only accepted a character as the second argument, where 1.3 takes a string.

For reference: [String.trim/2 in 1.2.6](https://hexdocs.pm/elixir/1.2.6/String.html#strip/2) vs. [String.trim/2 in 1.3.4](https://hexdocs.pm/elixir/1.3.4/String.html#trim/2)
